name: Create Resource By Type

on:
  workflow_dispatch:
    inputs:
      resourceType:
        type: choice
        description: Available resource types
        required: true
        default: 'monitors'
        options:
          - monitors
          - slos
          - dashboards
      environmentVar:
        type: choice
        description: Environment to add resource to
        required: true
        default: 'dev'
        options:
          - dev
          - prod
      jsonInput:
        description: Exported monitor json
        required: true
        type: string
        default: 'test'

env:
  SCRIPTS_DIR: src/scripts
  SCRIPT_NAME: create_and_write_function.py
  BRANCH_NAME: new-resource-by-type-${{ github.run_id }}-${{ github.run_attempt }}
  ENVIRONMENT: ${{ github.event.inputs.environmentVar }}
  RESOURCE_TYPE: ${{ github.event.inputs.resourceType }}
  JSON_INPUT: ${{ github.event.inputs.jsonInput }}

jobs:
  CreateResourceByType:
    name: Create Resource By Type
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate & write new function to file
        run: python ${{ env.SCRIPTS_DIR }}/${{ env.SCRIPT_NAME }} ${{ env.ENVIRONMENT }} ${{ env.RESOURCE_TYPE }} ${{ env.JSON_INPUT }}
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "feat: "
          commit_message: "Create a new resource template by type"
          target_branch: ${{ env.BRANCH_NAME }}
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          source_branch: ${{ env.BRANCH_NAME }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Create resource template by type"
          title: ${{ github.event.commits[0].message }}